# Autogenerated file, see mustache folder if you want to overwrite this file

####
# Network Rule Collection
####
resource "azurerm_firewall_network_rule_collection" "infra_common_services-ncol1" {
  name                = "infra_common_services-ncol1"
  azure_firewall_name = "${azurerm_firewall.fw.name}"
  resource_group_name = "${azurerm_firewall.fw.resource_group_name}"
  priority            = 100
  action              = "Allow"

  rule {
    name                  = "dns-rule1"
    source_addresses      = ["198.18.2.0/24"]
    destination_ports     = ["53"]
    destination_addresses = ["*"]
    protocols             = ["TCP", "UDP"]
  }

}

####
# Application Rule Collection
####
resource "azurerm_firewall_application_rule_collection" "infra_common_services-acol1" {
  name                = "infra_common_services-acol1"
  azure_firewall_name = "${azurerm_firewall.fw.name}"
  resource_group_name = "${azurerm_firewall.fw.resource_group_name}"
  priority            = 100
  action              = "Allow"

  rule {
    name             = "AzureTags-All-rule1"
    source_addresses = ["198.18.2.0/24"]
    fqdn_tags        = ["MicrosoftActiveProtectionService", "WindowsDiagnostics", "WindowsUpdate", "AppServiceEnvironment", "AzureBackup"]
  }
  rule {
    name             = "SecopsFqdn-rule1"
    source_addresses = ["198.18.2.0/24"]
    target_fqdns     = ["*.google.com", "*.bing.com"]

      protocol {
        port =  443
        type =  "Https"
      }
      protocol {
        port =  80
        type =  "Http"
      }
  }
}

####

